all: \
saddle-node-bifurcation-x-dxdt.eps \
pitchfork-bifurcation-x-dxdt.eps \
l1.eps l2.eps vdp.eps lorenz.eps \
chua-0.eps chua-1.eps chua-2.eps chua-3.eps chua-4.eps chua-5.eps \
rosser-0.eps rosser-1.eps rosser-2.eps rosser-3.eps rosser-4.eps \
rosser-5.eps rosser-6.eps rosser-7.eps rosser-8.eps \
ctrnn-0.eps ctrnn-1.eps ctrnn-2.eps ctrnn-3.eps \
ctrnn-4.eps ctrnn-5.eps ctrnn-6.eps ctrnn-7.eps \
ctrnn-8.eps ctrnn-9.eps ctrnn-10.eps ctrnn-11.eps \


saddle-node-bifurcation-x-dxdt.eps:../../svg/saddle-node-bifurcation-x-dxdt.eps
	cp $< $@

pitchfork-bifurcation-x-dxdt.eps:../../svg/pitchfork-bifurcation-x-dxdt.eps
	cp $< $@

l1.eps: ../../scripts/l1.png
	convert -trim $< $@

l2.eps: ../../scripts/l2.png
	convert -trim $< $@

vdp.eps: ../../scripts/vdp.png
	convert -trim $< $@

lorenz.eps: ../../scripts/lorenz.png
	convert -trim $< $@

chua-0.eps: ../../scripts/chua-0.png
	convert -trim $< $@
chua-1.eps: ../../scripts/chua-1.png
	convert -trim $< $@
chua-2.eps: ../../scripts/chua-2.png
	convert -trim $< $@
chua-3.eps: ../../scripts/chua-3.png
	convert -trim $< $@
chua-4.eps: ../../scripts/chua-4.png
	convert -trim $< $@
chua-5.eps: ../../scripts/chua-5.png
	convert -trim $< $@

rosser-0.eps:../../scripts/rosser-0.png
	convert -trim $< $@
rosser-1.eps:../../scripts/rosser-1.png
	convert -trim $< $@
rosser-2.eps:../../scripts/rosser-2.png
	convert -trim $< $@
rosser-3.eps:../../scripts/rosser-3.png
	convert -trim $< $@
rosser-4.eps:../../scripts/rosser-4.png
	convert -trim $< $@
rosser-5.eps:../../scripts/rosser-5.png
	convert -trim $< $@
rosser-6.eps:../../scripts/rosser-6.png
	convert -trim $< $@
rosser-7.eps:../../scripts/rosser-7.png
	convert -trim $< $@
rosser-8.eps:../../scripts/rosser-8.png
	convert -trim $< $@

ctrnn-0.eps:../../scripts/ctrnn-0.png
	convert -trim $< $@
ctrnn-1.eps:../../scripts/ctrnn-1.png
	convert -trim $< $@
ctrnn-2.eps:../../scripts/ctrnn-2.png
	convert -trim $< $@
ctrnn-3.eps:../../scripts/ctrnn-3.png
	convert -trim $< $@
ctrnn-4.eps:../../scripts/ctrnn-4.png
	convert -trim $< $@
ctrnn-5.eps:../../scripts/ctrnn-5.png
	convert -trim $< $@
ctrnn-6.eps:../../scripts/ctrnn-6.png
	convert -trim $< $@
ctrnn-7.eps:../../scripts/ctrnn-7.png
	convert -trim $< $@
ctrnn-8.eps:../../scripts/ctrnn-8.png
	convert -trim $< $@
ctrnn-9.eps:../../scripts/ctrnn-9.png
	convert -trim $< $@
ctrnn-10.eps:../../scripts/ctrnn-10.png
	convert -trim $< $@
ctrnn-11.eps:../../scripts/ctrnn-11.png
	convert -trim $< $@
